source "https://api.berkshelf.com"

cookbook 'build-essential'
cookbook 'yum-epel'
cookbook 'yum-remi'
cookbook 'yum-ius'
cookbook 'localedef', path: './site-cookbooks/localedef/'
cookbook 'apache', path: './site-cookbooks/apache/'
cookbook 'php', path: './site-cookbooks/php/'
cookbook 'mysql', path: './site-cookbooks/mysql/'
cookbook 'wordpress', path: './site-cookbooks/wordpress/'
